In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

In [37]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv'

In [38]:
!wget $data -O data-week-3.csv

--2021-09-22 10:38:38--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 977501 (955K) [text/plain]
Saving to: 'data-week-3.csv'

     0K .......... .......... .......... .......... ..........  5% 1.43M 1s
    50K .......... .......... .......... .......... .......... 10% 4.75M 0s
   100K .......... .......... .......... .......... .......... 15% 2.54M 0s
   150K .......... .......... .......... .......... .......... 20% 7.83M 0s
   200K .......... .......... .......... .......... .......... 26% 3.16M 0s
   250K .......... .......... .......... .......... .......... 31% 6.62M 0s
   300K .......... .......... .......... .......... .......... 36% 8.18M 0s
   350K .......... .......... .......... .......... .......... 41% 2.40M 0s
   400K .......... .......... .......... .......... .......... 47% 11.9M 0s
   450K .......... .......... .......... .......... .......... 52% 9.19M 0s
   500K .......... .......... .......... .......... .......... 57% 10.8M 0s
   550K .......... .......... .......... .......... .......... 62% 9.39M 0s
   600K .......... .......... .......... .......... .......... 68% 8.73M 0s
   650K .......... .......... .......... .......... .......... 73% 10.3M 0s
   700K .......... .......... .......... .......... .......... 78% 10.5M 0s
   750K .......... .......... .......... .......... .......... 83% 7.60M 0s
   800K .......... .......... .......... .......... .......... 89% 10.9M 0s
   850K .......... .......... .......... .......... .......... 94% 9.21M 0s
   900K .......... .......... .......... .......... .......... 99% 9.36M 0s
   950K ....                                                  100% 12.7M=0.2s

2021-09-22 10:38:39 (5.33 MB/s) - 'data-week-3.csv' saved [977501/977501]

In [40]:
df = pd.read_csv('data-week-3.csv')
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [41]:
df.head().T

,0,1,2,3,4
customerID,7590-VHVEG,5575-GNVDE,3668-QPYBK,7795-CFOCW,9237-HQITU
gender,Female,Male,Male,Male,Female
SeniorCitizen,0,0,0,0,0
Partner,Yes,No,No,No,No
Dependents,No,No,No,No,No
tenure,1,34,2,45,2
PhoneService,No,Yes,Yes,No,Yes
MultipleLines,No phone service,No,No,No phone service,No
InternetService,DSL,DSL,DSL,DSL,Fiber optic
OnlineSecurity,No,Yes,Yes,Yes,No
OnlineBackup,Yes,No,Yes,No,No
DeviceProtection,No,Yes,No,Yes,No
TechSupport,No,No,No,Yes,No
StreamingTV,No,No,No,No,No
StreamingMovies,No,No,No,No,No
Contract,Month-to-month,One year,Month-to-month,One year,Month-to-month
PaperlessBilling,Yes,No,Yes,No,Yes
PaymentMethod,Electronic check,Mailed check,Mailed check,Bank transfer (automatic),Electronic check
MonthlyCharges,29.85,56.95,53.85,42.3,70.7
TotalCharges,29.85,1889.5,108.15,1840.75,151.65
Churn,No,No,Yes,No,Yes

In [43]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [45]:
df.columns = df.columns.str.lower().str.replace(' ','_')

In [46]:
df.columns

Index(['customerid', 'gender', 'seniorcitizen', 'partner', 'dependents',
       'tenure', 'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod', 'monthlycharges', 'totalcharges', 'churn'],
      dtype='object')

In [49]:
df.head().T

,0,1,2,3,4
customerid,7590-VHVEG,5575-GNVDE,3668-QPYBK,7795-CFOCW,9237-HQITU
gender,Female,Male,Male,Male,Female
seniorcitizen,0,0,0,0,0
partner,Yes,No,No,No,No
dependents,No,No,No,No,No
tenure,1,34,2,45,2
phoneservice,No,Yes,Yes,No,Yes
multiplelines,No phone service,No,No,No phone service,No
internetservice,DSL,DSL,DSL,DSL,Fiber optic
onlinesecurity,No,Yes,Yes,Yes,No
onlinebackup,Yes,No,Yes,No,No
deviceprotection,No,Yes,No,Yes,No
techsupport,No,No,No,Yes,No
streamingtv,No,No,No,No,No
streamingmovies,No,No,No,No,No
contract,Month-to-month,One year,Month-to-month,One year,Month-to-month
paperlessbilling,Yes,No,Yes,No,Yes
paymentmethod,Electronic check,Mailed check,Mailed check,Bank transfer (automatic),Electronic check
monthlycharges,29.85,56.95,53.85,42.3,70.7
totalcharges,29.85,1889.5,108.15,1840.75,151.65
churn,No,No,Yes,No,Yes

In [52]:
categorical_columns = list(df.dtypes[df.dtypes=='object'].index)

In [53]:
categorical_columns

['customerid',
 'gender',
 'partner',
 'dependents',
 'phoneservice',
 'multiplelines',
 'internetservice',
 'onlinesecurity',
 'onlinebackup',
 'deviceprotection',
 'techsupport',
 'streamingtv',
 'streamingmovies',
 'contract',
 'paperlessbilling',
 'paymentmethod',
 'totalcharges',
 'churn']

In [54]:
df['gender']

0       Female
1         Male
2         Male
3         Male
4       Female
         ...
7038      Male
7039    Female
7040    Female
7041      Male
7042      Male
Name: gender, Length: 7043, dtype: object

In [56]:
for c in categorical_columns:
    df[c] = df[c].str.lower().str.replace(' ','_')

In [57]:
df.head().T

,0,1,2,3,4
customerid,7590-vhveg,5575-gnvde,3668-qpybk,7795-cfocw,9237-hqitu
gender,female,male,male,male,female
seniorcitizen,0,0,0,0,0
partner,yes,no,no,no,no
dependents,no,no,no,no,no
tenure,1,34,2,45,2
phoneservice,no,yes,yes,no,yes
multiplelines,no_phone_service,no,no,no_phone_service,no
internetservice,dsl,dsl,dsl,dsl,fiber_optic
onlinesecurity,no,yes,yes,yes,no
onlinebackup,yes,no,yes,no,no
deviceprotection,no,yes,no,yes,no
techsupport,no,no,no,yes,no
streamingtv,no,no,no,no,no
streamingmovies,no,no,no,no,no
contract,month-to-month,one_year,month-to-month,one_year,month-to-month
paperlessbilling,yes,no,yes,no,yes
paymentmethod,electronic_check,mailed_check,mailed_check,bank_transfer_(automatic),electronic_check
monthlycharges,29.85,56.95,53.85,42.3,70.7
totalcharges,29.85,1889.5,108.15,1840.75,151.65
churn,no,no,yes,no,yes

In [58]:
df.dtypes

customerid           object
gender               object
seniorcitizen         int64
partner              object
dependents           object
tenure                int64
phoneservice         object
multiplelines        object
internetservice      object
onlinesecurity       object
onlinebackup         object
deviceprotection     object
techsupport          object
streamingtv          object
streamingmovies      object
contract             object
paperlessbilling     object
paymentmethod        object
monthlycharges      float64
totalcharges         object
churn                object
dtype: object

In [59]:
df.totalcharges

0         29.85
1        1889.5
2        108.15
3       1840.75
4        151.65
         ...
7038     1990.5
7039     7362.9
7040     346.45
7041      306.6
7042     6844.5
Name: totalcharges, Length: 7043, dtype: object

In [60]:
df.totalcharges = pd.to_numeric(df.totalcharges,errors='coerce')

In [63]:
df.totalcharges.isnull()

0       False
1       False
2       False
3       False
4       False
        ...
7038    False
7039    False
7040    False
7041    False
7042    False
Name: totalcharges, Length: 7043, dtype: bool

In [64]:
df[df.totalcharges.isnull()][['customerid','totalcharges']]

      customerid  totalcharges
488   4472-lvygi           NaN
753   3115-czmzd           NaN
936   5709-lvoeq           NaN
1082  4367-nuyao           NaN
1340  1371-dwpaz           NaN
3331  7644-omvmy           NaN
3826  3213-vvolg           NaN
4380  2520-sgtta           NaN
5218  2923-arzlg           NaN
6670  4075-wkniu           NaN
6754  2775-sefee           NaN

In [65]:
df.totalcharges = df.totalcharges.fillna(0)

In [66]:
df[df.totalcharges.isnull()][['customerid','totalcharges']]

Empty DataFrame
Columns: [customerid, totalcharges]
Index: []

In [67]:
df.churn

0        no
1        no
2       yes
3        no
4       yes
       ...
7038     no
7039     no
7040     no
7041    yes
7042     no
Name: churn, Length: 7043, dtype: object

In [68]:
df.churn = (df.churn=='yes').astype(int)

In [69]:
df.churn

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: churn, Length: 7043, dtype: int32